name: Android CI

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download WebRTC
      run: mkdir libs && wget -O libs/libwebrtc-m92.aar https://gultsch.de/files/libwebrtc-m92.aar
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Build Snikket (Compat)
    #  run: ./gradlew assembleConversationsFreeCompatDebug
    - name: Build Snikket (System)
      run: ./gradlew assembleConversationsFreeSystemDebug
    - uses: actions/upload-artifact@v2
      with:
        name: Snikket all-flavors (debug)
        path: ./build/outputs/apk/**/debug/Snikket-*.apk

      
